# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: /hy-tmp/exp/eat/logs/shipsear_uteat_pretrain/tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: true
  user_dir: /hy-tmp/eat_work/EAT
  seed: 42

checkpoint:
  save_interval: 1
  save_interval_updates: 2000
  keep_interval_updates: 2
  no_epoch_checkpoints: true
  save_dir: /hy-tmp/exp/eat/runs/shipsear_uteat_pretrain

task:
  _name: mae_image_pretraining
  data: /hy-tmp/exp/eat/manifests/shipsear
  rebuild_batches: true
  key: source
  precompute_mask_config: {}
  downsr_16hz: true
  audio_mae: true
  h5_format: false
  target_length: 1024
  flexible_mask: false

dataset:
  num_workers: 6
  batch_size: 8
  skip_invalid_size_inputs_valid_test: true
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 1
  ddp_backend: c10d

criterion:
  _name: model
  log_keys: [ema_decay, target_var, pred_var, model_norm, ema_norm, masked_pct]

optimization:
  max_update: 120000
  lr: [0.0005]
  clip_norm: 4
  update_freq: [2]

optimizer:
  _name: composite
  dynamic_groups: true
  groups:
    default:
      lr_float: 0.0005
      optimizer:
        _name: adam
        adam_betas: [0.9,0.95]
        weight_decay: 0.05
      lr_scheduler:
        _name: cosine
        warmup_updates: 10000

lr_scheduler: pass_through

model:
  _name: data2vec_multi
  backbone_variant: uteat
  depth: 6
  embed_dim: 384
  num_heads: 6
  mlp_ratio: 3
  light_conv_kernel: 5
  light_mlp_ratio: 2.0
  light_num_heads: 6
  average_top_k_layers: 6
  clone_batch: 16

  ema_decay: 0.9998
  ema_end_decay: 0.99999
  ema_anneal_end_step: 100000
  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: true
  end_of_block_targets: false
  norm_eps: 1e-6

  cls_loss: 1
  recon_loss: 0.5
  d2v_loss: 1
  physical_loss_weight: 0.2
  physical_num_bands: 4

  supported_modality: IMAGE
  ema_encoder_only: false

  modalities:
    image:
      in_chans: 1
      inverse_mask: true
      mask_prob: 0.8
      mask_prob_adjust: 0.07
      mask_length: 5
      mask_strategy: uteat_phys
      low_freq_ratio: 0.35
      low_freq_mask_prob_mult: 1.4
      mask_noise_std: 0.01
      prenet_depth: 0
      ema_local_encoder: true
      num_extra_tokens: 1
      init_extra_token_zero: false
      use_alibi_encoder: false
      decoder:
        decoder_dim: 384
        decoder_groups: 16
        decoder_kernel: 3
        decoder_layers: 4
        input_dropout: 0
