# @package _group_

defaults:
  - /pretraining_shipsear_uteat_formal

common:
  tensorboard_logdir: /hy-tmp/exp/eat/logs/ablation_shipsear_ut_backbone_pretrain/tb

checkpoint:
  save_dir: /hy-tmp/exp/eat/runs/ablation_shipsear_ut_backbone_pretrain

model:
  backbone_variant: uteat
  physical_loss_weight: 0.0
  modalities:
    image:
      mask_strategy: baseline

optimization:
  max_update: 10000
